const HINTS = ["Proporcija — dviejų santykių lygybė. Pagrindinė savybė: kraštinių narių sandauga lygi vidinių narių sandaugai (a·d = b·c).","Kraštiniai — pirmas ir paskutinis narys; vidiniai — du viduryje. Sudaugink žinomus ir sudaryk lygybę su x.","Užrašyk sandaugų lygybę: kraštinis · kraštinis = vidinis · vidinis. Vienoje pusėje bus x.","Suskaičiuok žinomų narių sandaugą — tai skaičius, kuriam turi būti lygi kita sandauga su x.","Kai gauni pavidalą „x · skaičius = skaičius“, x rasi padalinęs dešinę pusę iš skaičiaus prie x.","Nesumaišyk narių: dauginam kraštinį su kraštiniu, o ne du vieno santykio narius.","Patikrink save: įstatęs rastą x atgal, abi sandaugos (kraštinių ir vidinių) turi sutapti.","Jei nežinomasis yra vidurinis narys, jis vis tiek randamas iš tos pačios lygybės a·d = b·c.","Atsakymas — vienaženklis skaičius (0–9). Jei gavai daugiaženklį, patikrink dauginimą.","Užrašyk lygybę tvarkingai ir suskaičiuok pats — kiekvienas ratukas duoda po vieną kodo skaitmenį."];

const VARIANTS = [
 [
  { title:"Seifo ratukas Nr. 1", eq:"x : 2 = 6 : 4  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 2 = 6 : 4 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:3 },
  { title:"Seifo ratukas Nr. 2", eq:"3 : x = 6 : 8  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 3 : x = 6 : 8 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:4 },
  { title:"Atbulinė spyna", eq:"x : 5 = 4 : 10  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 5 = 4 : 10 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:2 },
  { title:"Trupmenos kodas", eq:"6 : 3 = x : 4  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 6 : 3 = x : 4 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:8 },
  { title:"Antra atbulinė spyna", eq:"2 : x = 4 : 10  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 2 : x = 4 : 10 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:5 },
  { title:"Dalininko užraktas", eq:"x : 6 = 1 : 6  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 6 = 1 : 6 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:1 },
  { title:"Skaitmenų grotelės", eq:"4 : 2 = x : 3  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 4 : 2 = x : 3 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:6 },
  { title:"Sargybos mįslė", eq:"x : 3 = 3 : 9  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 3 = 3 : 9 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:1 },
  { title:"Priešpaskutinė spyna", eq:"x : 4 = 3 : 6  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 4 = 3 : 6 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:2 },
  { title:"Pabėgimo mįslė", eq:"x : 9 = 1 : 3  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 9 = 1 : 3 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:3 },
 ],
 [
  { title:"Seifo ratukas Nr. 1", eq:"x : 3 = 4 : 6  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 3 = 4 : 6 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:2 },
  { title:"Seifo ratukas Nr. 2", eq:"2 : x = 4 : 8  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 2 : x = 4 : 8 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:4 },
  { title:"Atbulinė spyna", eq:"x : 4 = 3 : 6  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 4 = 3 : 6 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:2 },
  { title:"Trupmenos kodas", eq:"8 : 4 = x : 3  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 8 : 4 = x : 3 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:6 },
  { title:"Antra atbulinė spyna", eq:"3 : x = 6 : 10  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 3 : x = 6 : 10 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:5 },
  { title:"Dalininko užraktas", eq:"x : 7 = 1 : 7  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 7 = 1 : 7 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:1 },
  { title:"Skaitmenų grotelės", eq:"6 : 3 = x : 4  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 6 : 3 = x : 4 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:8 },
  { title:"Sargybos mįslė", eq:"x : 2 = 4 : 8  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 2 = 4 : 8 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:1 },
  { title:"Priešpaskutinė spyna", eq:"x : 5 = 6 : 10  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 5 = 6 : 10 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:3 },
  { title:"Pabėgimo mįslė", eq:"9 : x = 3 : 3  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 9 : x = 3 : 3 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:9 },
 ],
 [
  { title:"Seifo ratukas Nr. 1", eq:"x : 4 = 6 : 8  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 4 = 6 : 8 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:3 },
  { title:"Seifo ratukas Nr. 2", eq:"4 : x = 2 : 4  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 4 : x = 2 : 4 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:8 },
  { title:"Atbulinė spyna", eq:"x : 6 = 2 : 4  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 6 = 2 : 4 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:3 },
  { title:"Trupmenos kodas", eq:"5 : 2 = x : 2  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 5 : 2 = x : 2 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:5 },
  { title:"Antra atbulinė spyna", eq:"2 : x = 3 : 9  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 2 : x = 3 : 9 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:6 },
  { title:"Dalininko užraktas", eq:"x : 8 = 1 : 8  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 8 = 1 : 8 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:1 },
  { title:"Skaitmenų grotelės", eq:"6 : 3 = x : 2  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 6 : 3 = x : 2 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:4 },
  { title:"Sargybos mįslė", eq:"x : 4 = 3 : 6  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 4 = 3 : 6 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:2 },
  { title:"Priešpaskutinė spyna", eq:"x : 6 = 5 : 10  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 6 = 5 : 10 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:3 },
  { title:"Pabėgimo mįslė", eq:"8 : x = 2 : 2  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 8 : x = 2 : 2 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:8 },
 ],
 [
  { title:"Seifo ratukas Nr. 1", eq:"x : 6 = 2 : 4  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 6 = 2 : 4 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:3 },
  { title:"Seifo ratukas Nr. 2", eq:"5 : x = 5 : 3  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 5 : x = 5 : 3 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:3 },
  { title:"Atbulinė spyna", eq:"x : 3 = 8 : 12  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 3 = 8 : 12 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:2 },
  { title:"Trupmenos kodas", eq:"9 : 3 = x : 2  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 9 : 3 = x : 2 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:6 },
  { title:"Antra atbulinė spyna", eq:"4 : x = 3 : 6  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 4 : x = 3 : 6 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:8 },
  { title:"Dalininko užraktas", eq:"x : 9 = 1 : 9  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 9 = 1 : 9 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:1 },
  { title:"Skaitmenų grotelės", eq:"8 : 4 = x : 3  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 8 : 4 = x : 3 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:6 },
  { title:"Sargybos mįslė", eq:"x : 4 = 2 : 4  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 4 = 2 : 4 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:2 },
  { title:"Priešpaskutinė spyna", eq:"x : 7 = 4 : 4  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje x : 7 = 4 : 4 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:7 },
  { title:"Pabėgimo mįslė", eq:"2 : x = 4 : 8  (x = ?)", q:"Rask nežinomą proporcijos narį x proporcijoje 2 : x = 4 : 8 ir įrašyk jį kaip šio ratuko kodo skaitmenį.", ans:4 },
 ]
];
